### PR TITLE
added test and entry in  Street_Type for "Row"

### PR DESCRIPTION
**Pull request by knaopel**
Had an address that was not properly because the street type was "Row".

### CODE REVIEW

**Comment by hassansin** [comment]
Merged, thanks for the PR!

**Comment by knaopel** [comment]
Will you update the NPM as well?

Thanks!

**Comment by hassansin** [comment]
yes, bumped version and published to NPM.

**Comment by knaopel** [comment]
??

Sent from my mobile phone.

________________________________

**Pull request merged**
